#ifndef prism_lexer_h
#define prism_lexer_h

typedef enum {
  TOKEN_LEFT_PAREN, TOKEN_RIGHT_PAREN,
  TOKEN_LEFT_BRACE, TOKEN_RIGHT_BRACE,
  TOKEN_LEFT_BRACKET, TOKEN_RIGHT_BRACKET,
  TOKEN_COMMA, TOKEN_DOT, TOKEN_MINUS, TOKEN_PLUS,
  TOKEN_SEMICOLON, TOKEN_SLASH, TOKEN_STAR, TOKEN_PERCENT,
  TOKEN_AMP, TOKEN_PIPE, TOKEN_CARET, TOKEN_TILDE,
  TOKEN_SHIFT_LEFT, TOKEN_SHIFT_RIGHT,
  TOKEN_ARROW, TOKEN_COLON, TOKEN_QUESTION, TOKEN_PRINT,

  TOKEN_PLUS_PLUS, TOKEN_MINUS_MINUS,

  TOKEN_AMP_AMP, TOKEN_PIPE_PIPE,

  TOKEN_PLUS_EQUAL, TOKEN_MINUS_EQUAL, TOKEN_STAR_EQUAL,
  TOKEN_SLASH_EQUAL, TOKEN_PERCENT_EQUAL, TOKEN_AMP_EQUAL,
  TOKEN_PIPE_EQUAL, TOKEN_CARET_EQUAL,
  TOKEN_SHIFT_LEFT_EQUAL, TOKEN_SHIFT_RIGHT_EQUAL,

  TOKEN_BANG, TOKEN_BANG_EQUAL,
  TOKEN_EQUAL, TOKEN_EQUAL_EQUAL,
  TOKEN_GREATER, TOKEN_GREATER_EQUAL,
  TOKEN_LESS, TOKEN_LESS_EQUAL,

  TOKEN_IDENTIFIER, TOKEN_STRING, TOKEN_NUMBER,
  TOKEN_CHAR,

  TOKEN_AND, TOKEN_OR, TOKEN_ELSE, TOKEN_FALSE, TOKEN_TRUE, TOKEN_NIL,
  TOKEN_FOR, TOKEN_FUN, TOKEN_IF, TOKEN_RETURN, TOKEN_VAR, TOKEN_WHILE,
  TOKEN_STRUCT,

  TOKEN_UNION,      
  TOKEN_DO,         
  TOKEN_SWITCH,     
  TOKEN_CASE,       
  TOKEN_DEFAULT,    
  TOKEN_BREAK,      
  TOKEN_CONTINUE,   
  TOKEN_GOTO,       
  TOKEN_SIZEOF,     
  TOKEN_STATIC,     
  TOKEN_EXTERN,    
  TOKEN_AS,       
  TOKEN_PACKED,
  TOKEN_SECTION,

  TOKEN_ERROR, TOKEN_EOF
} TokenType;

typedef struct {
  TokenType type;
  const char* start;
  int length;
  int line;
  int col;  
} Token;

typedef struct {
  const char* start;
  const char* current;
  const char* lineStart;   
  int line;
} Lexer;

extern Lexer lexer;

void initLexer(const char* source);   
Token scanToken(void);

#endif
